### ISSUE TITLE
Add implementation of btHresult.

### ISSUE THREAD

**Issue by NoviceLive** [LibreCrops/cdef#2]
# Description

The lack of implementation for `btHresult` caused a considerable number of crashes, including some high-profile or non-trivial PDB files such as `urlmon.pdb` and `ole32.pdb`.
# References
- [[MS-ERREF]: HRESULT](https://msdn.microsoft.com/en-us/library/cc231198.aspx)
# Sample

It comes from Windows 7 x64.

[ole32.pdb](http://pan.baidu.com/s/1i3tpyQx)
# Output

```
F:\repo\PdbReader>PdbReader\bin\Debug\PdbReader.exe xml c:\Symbols\ole32.pdb\EE489189724F4D47AECCFDB5534824352\ole32.pdb

Unhandled Exception: System.NotImplementedException: btHresult
   at PdbReader.Translator._TranslateBaseType(IDiaSymbol sym) in \\vboxsvr\novicelive\repo\PdbReader\PdbReader\Translator.cs:line 85
   at PdbReader.Translator.TranslateBaseType(IDiaSymbol sym) in \\vboxsvr\novicelive\repo\PdbReader\PdbReader\Translator.cs:line 90
   at PdbReader.Translator.Translate(IDiaSymbol sym) in \\vboxsvr\novicelive\repo\PdbReader\PdbReader\Translator.cs:line 19
   at PdbReader.Translator.TranslateFunc(IDiaSymbol sym) in \\vboxsvr\novicelive\repo\PdbReader\PdbReader\Translator.cs:line 105
   at PdbReader.Translator.Translate(IDiaSymbol sym) in \\vboxsvr\novicelive\repo\PdbReader\PdbReader\Translator.cs:line 28
   at PdbReader.Translator.TranslatePtr(IDiaSymbol sym) in \\vboxsvr\novicelive\repo\PdbReader\PdbReader\Translator.cs:line 94
   at PdbReader.Translator.Translate(IDiaSymbol sym) in \\vboxsvr\novicelive\repo\PdbReader\PdbReader\Translator.cs:line 22
   at PdbReader.Translator.TranslateMember(IDiaSymbol subSym) in \\vboxsvr\novicelive\repo\PdbReader\PdbReader\Translator.cs:line 128
   at PdbReader.Translator.TranslateStruct(IDiaSymbol sym) in \\vboxsvr\novicelive\repo\PdbReader\PdbReader\Translator.cs:line 149
   at PdbReader.PdbSymbolType.Type_Struct.Translate(Translator translator, IDiaSymbol symbol) in \\vboxsvr\novicelive\repo\PdbReader\PdbReader\PdbSymbolType.cs:line 20
   at PdbReader.PdbSymbol.TranslateBy(Translator translator) in \\vboxsvr\novicelive\repo\PdbReader\PdbReader\PdbSymbol.cs:line 42
   at PdbReader.AppAction.Action_Xml.Execute(App app) in \\vboxsvr\novicelive\repo\PdbReader\PdbReader\AppAction.cs:line 33
   at PdbReader.App.Run() in \\vboxsvr\novicelive\repo\PdbReader\PdbReader\App.cs:line 61
   at PdbReader.Program.Main(String[] args) in \\vboxsvr\novicelive\repo\PdbReader\PdbReader\Program.cs:line 17
```

**Comment by kbridge** [comment]
fixed.
